import Vue from 'vue'
import { Button, Calendar, Cell, CellGroup, Tabbar, TabbarItem, NavBar, Field, Toast, Search, Swipe, SwipeItem, SwipeCell, Grid, GridItem, Icon, Rate, ActionSheet, Stepper, Loading, Dialog, Checkbox, Card, AddressList, AddressEdit, Area, Tab, Tabs } from 'vant'
Vue.use(Button)
Vue.use(Calendar)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Field)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(SwipeCell)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Stepper)
Vue.use(Loading)
Vue.use(Checkbox)
Vue.use(Card)
Vue.use(AddressList)
Vue.use(AddressEdit)
Vue.use(Area)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Dialog)
Vue.prototype.$toast = Toast
Vue.prototype.$dialog = Dialog
